site_name: DiffUSE Logbook
nav:
  - Home: index.md
  - Posts: 
    - log/index.md
    - log/tags.md
theme: 
  icon:
    logo: fontawesome/solid/book-open
  name: material
  palette:
    primary: blue grey
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
plugins:
  - tags
  - blog:
      authors: true
      blog_dir: log
      blog_toc: true
      post_url_format: '{file}'
      post_readtime: false
      archive: false
      categories_allowed:
        - Analysis
        - Data