site_name: DiffUSE Logbook
theme: 
  icon:
    logo: fontawesome/solid/book-open
  name: material
  palette:
    #scheme: slate
    #primary: purple
    #accent: pink
  features:
#    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
plugins:
  - tags
  - blog:
      authors: true
      blog_dir: analysis
      blog_toc: true
      post_url_format: '{file}'
      post_readtime: false
      archive: false