site_name: "Logbook"
repo_url: https://github.com/diff-use/logbook
site_url: https://diffuse.science/logbook
site_description: "A logbook for the Diffuse Project"
site_author: "The Diffuse Project"
extra:
  homepage: https://diffuse.science
  homepage_title: The Diffuse Project
  generator: true
extra_css:
  - stylesheets/extra.css
copyright: "&copy; 2025 The Diffuse Project."
theme: 
  logo: assets/diffuse-logo-dark-sm.png
  name: material
  custom_dir: overrides
  palette:
    primary: black
    accent: orange
  features:
#    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
plugins:
  - tags
  - blog:
      authors: true
      blog_dir: analysis
      blog_toc: true
      post_url_format: '{file}'
      post_readtime: false
      archive: false