authors:
  spmeisburger:
    name: Steve Meisburger
    description: Research scientist at Cornell / CHESS
    avatar: https://github.com/diff-use/diff-use.github.io/blob/main/assets/images/members/meisburger.jpg?raw=true
    url: https://spmeisburger.github.io
    slug: steve